[package]
name = "hyprconfig"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "2.1", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hyprland = "0.4.0-beta.2"

[build-dependencies]
tauri-build = { version = "2.1", features = [] }
